# -*- coding: utf-8 -*-
"""easy_ocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLjC7J4SU-IZLHkNTqgOee_eVkNyi959
"""

import matplotlib.pyplot as plt
import easyocr
import cv2
img=cv2.imread('./test-images/stockimage1.jpg')

reader = easyocr.Reader(['en'])
results = reader.readtext(img)
print(results)

for (bbox, text, prob) in results:
    print(text)
plt.imshow(img)
plt.title("First Image")
plt.show()